import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "react-phone-input-2/lib/style.css";
import "./globals.css";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Awabah-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <div className="flex flex-col">{children}</div>
      </body>
    </html>
  );
}
